# Generated by Django 4.1.2 on 2022-10-24 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='itemsForSell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=15)),
                ('image', models.ImageField(upload_to='images/')),
                ('is_on_sale', models.BooleanField(default=False)),
            ],
        ),
    ]
