# Generated by Django 4.1.2 on 2022-11-05 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
        ),
    ]
