# Generated by Django 4.1.2 on 2022-11-05 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_menu', '0005_alter_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsforsell',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game_menu.category', verbose_name='категория'),
        ),
    ]
