# Generated by Django 4.1.2 on 2022-11-05 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_menu', '0006_itemsforsell_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemsforsell',
            name='category',
        ),
        migrations.AddField(
            model_name='itemsforsell',
            name='category',
            field=models.ManyToManyField(to='game_menu.category', verbose_name='категория'),
        ),
    ]
